[Color1Dot]
Meter=Shape
X=35
Y=60
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color1# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color1# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color1# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color1#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color2Dot]
Meter=Shape
X=75
Y=60
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color2# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color2# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color2# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color2#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color3Dot]
Meter=Shape
X=115
Y=60
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color3# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color3# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color3# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color3#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color4Dot]
Meter=Shape
X=155
Y=60
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color4# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color4# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color4# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color4#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color5Dot]
Meter=Shape
X=195
Y=60
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color5# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color5# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color5# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color5#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color6Dot]
Meter=Shape
X=35
Y=100
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color6# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color6# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color6# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color6#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color7Dot]
Meter=Shape
X=75
Y=100
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color7# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color7# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color7# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color7#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color8Dot]
Meter=Shape
X=115
Y=100
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color8# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color8# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color8# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color8#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color9Dot]
Meter=Shape
X=155
Y=100
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color9# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color9# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color9# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color9#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color10Dot]
Meter=Shape
X=195
Y=100
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color10# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color10# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color10# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color10#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color11Dot]
Meter=Shape
X=35
Y=140
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color11# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color11# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color11# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color11#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color12Dot]
Meter=Shape
X=75
Y=140
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color12# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color12# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color12# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color12#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color13Dot]
Meter=Shape
X=115
Y=140
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color13# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color13# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color13# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color13#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color14Dot]
Meter=Shape
X=155
Y=140
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color14# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color14# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color14# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color14#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color15Dot]
Meter=Shape
X=195
Y=140
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color15# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color15# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color15# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color15#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color16Dot]
Meter=Shape
X=35
Y=180
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color16# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color16# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color16# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color16#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color17Dot]
Meter=Shape
X=75
Y=180
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color17# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color17# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color17# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color17#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color18Dot]
Meter=Shape
X=115
Y=180
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color18# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color18# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color18# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color18#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color19Dot]
Meter=Shape
X=155
Y=180
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color19# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color19# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color19# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color19#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color20Dot]
Meter=Shape
X=195
Y=180
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color20# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color20# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color20# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color20#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color21Dot]
Meter=Shape
X=35
Y=220
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color21# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color21# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color21# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color21#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color22Dot]
Meter=Shape
X=75
Y=220
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color22# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color22# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color22# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color22#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color23Dot]
Meter=Shape
X=115
Y=220
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color23# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color23# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color23# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color23#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color24Dot]
Meter=Shape
X=155
Y=220
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color24# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color24# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color24# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color24#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color25Dot]
Meter=Shape
X=195
Y=220
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color25# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color25# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color25# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color25#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color26Dot]
Meter=Shape
X=35
Y=260
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color26# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color26# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color26# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color26#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color27Dot]
Meter=Shape
X=75
Y=260
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color27# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color27# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color27# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color27#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color28Dot]
Meter=Shape
X=115
Y=260
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color28# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color28# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color28# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color28#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color29Dot]
Meter=Shape
X=155
Y=260
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color29# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color29# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color29# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color29#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color30Dot]
Meter=Shape
X=195
Y=260
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color30# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color30# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color30# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color30#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color31Dot]
Meter=Shape
X=35
Y=300
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color31# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color31# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color31# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color31#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color32Dot]
Meter=Shape
X=75
Y=300
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color32# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color32# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color32# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color32#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color33Dot]
Meter=Shape
X=115
Y=300
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color33# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color33# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color33# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color33#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color34Dot]
Meter=Shape
X=155
Y=300
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color34# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color34# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color34# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color34#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

[Color35Dot]
Meter=Shape
X=195
Y=300
Shape=Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color35# | StrokeWidth 0 | Extend Glow
MouseOverAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,(#ColorDotSize#/2 + 2) | Fill Color #Color35# | StrokeWidth 0 | Extend GlowHover"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Shape "Ellipse (#ColorDotSize#/2),#ColorDotSize#/2,#ColorDotSize#/2 | Fill Color #Color35# | StrokeWidth 0 | Extend Glow"][!UpdateMeter *][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables TriggerBgColor "#Color35#" "#ROOTCONFIGPATH#MyTheme\\Welcome.ini"][!RefreshGroup catppuccin][!DeactivateConfig]
DynamicVariables=1
Group=ColorDots
Glow=
GlowHover=Blur 4

